config/routes.rb
Rails.application.routes.draw do
  root to: 'cities#index'

  resources :users, only: [:new, :create, :show]

  # get '/users', to: 'users#index', as: 'users'

  # get '/users/new', to: 'users#new', as: 'new_user'

  # post '/users', to: 'users#create'

  # get '/users/:id', to: 'users#show', as: 'user'

  get '/sign_in', to: 'sessions#new', as: 'new_session'

  resources :sessions, only: [:new, :create]
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :cities, only: [:index, :new, :create, :show] do 

  # get '/cities', to: 'cities#index', as: 'cities'

  # get '/cities/new', to: 'cities#new', as:'new_city'

  # post '/cities', to: 'cities#create'

  get '/cities/:id', to: 'cities#show', as: 'city'


  # get '/logout', to: 'cities#index'

    resources :posts, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  # get '/cities/:id/posts', to: 'posts#index', as: 'posts'

  # get '/cities/:id/posts/new', to: 'posts#new', as: 'new_post'

  # post '/cities/:id/posts', to: 'posts#create'

  # get '/cities/:id/posts/:id', to: 'posts#show'

end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :posts
  has_many :features

  # def features
  #   @kinds = ["Food & Bev", "Art", "Accomodations", "Misc."]
  # end

  after_create :create_features
  def create_features
    self.features << Feature.create(title: "Food & Bev")
    self.features << Feature.create(title: "Art")
    self.features << Feature.create(title: "Accomodations")
    self.features << Feature.create(title: "Micellaneous")
  end
end

app/models/feature.rb
class Feature < ActiveRecord::Base
	has_many :posts
  belongs_to :city
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :feature
	belongs_to :city
	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts

  attr_accessor :confirmation_code

  validates :email, presence: true, uniqueness: true, length: {minimum: 6}, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i}
  validates :password, presence: true

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  # def current_user
  # 	@current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  # end
	helper_method :current_user
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index 
    @cities = City.all
    render :index
  end

  def new 
    # @user = User.find_by(id: session[:user_id])
    @city = City.new
    render :new
  end

  def create
    city_params = params.require(:city).permit(:name, :url, :description)
    @city = City.create(city_params)
    redirect_to city_path(@city)
  end

  def show
    @city = City.find(params[:id])
    @posts = @city.posts
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new 
		# @city = City.find_by(id: params[:id])
    @city = City.find(params[:city_id])
    @city_id = @city.id.to_i
		# @feature = Feature.find(params[:feature_id])
		@post = Post.new
    @features = Feature.all
  
		render :new
	end

	def create
    if session[:user_params] == true
    end

		@post = Post.create(post_params)
		@city = City.find(params[:city_id])
		@post.city_id = @city.id
		# @feature = Feature.find(params[:feature_id])
		# @post.feature_id = @feature.id
		@current_user = current_user
		@post.user_id = @current_user.id
    @post.save!
		redirect_to city_path(@city)
	end

   def show
    @city = City.find(params[:id])
    @posts = @city.posts
  end

  def edit
    @city = City.find(params[:city_id])
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.destroy!
    @city = City.find(params[:city_id])
    @post = Post.create(post_params)
    redirect_to city_path(@city)
  end

  def destroy
    @city = City.find(params[:city_id])
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to city_path(@city)
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :imageUrl, :feature_id, :city_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by(email: user_params[:email])
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      login(@user) #login the user
      redirect_to @user #go to show page for user
    else
      @cities = City.all 
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'cities/index'
    end
  end

  def destroy
    p "current user session id is:"
    p session[:user_id]
    p "***" * 800
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :confirmation_code, :admin)
    
    if user_params[:confirmation_code] == "123abc"
       user_params[:admin] = true
    end
    p user_params
    @user = User.create(user_params)
    login(@user) # <-- login the user
    redirect_to @user # <-- go to show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    # use find_by instead of find because find blows up when it fails to find a user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to new_session_path
    end
  end

  def logout
    @current_user = session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_html_footer.html.erb
  <!-- begin #footer -->
        <div id="footer" class="footer">
           
                <div class="text-center">
                   <p class="footerColor" &copy; Copyright Obscura 2015 <br />
                    </p>
                </div>
                <p class="social-list">
                    <a href="#"><i class="fa fa-facebook fa-fw"></i></a>
                    <a href="#"><i class="fa fa-instagram fa-fw"></i></a>
                    <a href="#"><i class="fa fa-twitter fa-fw"></i></a>
                    <a href="#"><i class="fa fa-google-plus fa-fw"></i></a>
                    <a href="#"><i class="fa fa-dribbble fa-fw"></i></a>
                </p>
            </div>

  </div>

app/views/application/_html_header.html.erb
<head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Obscura</title>
         <!-- VENDOR SCRIPTS -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

      <!-- FONTS -->
      <link href='https://fonts.googleapis.com/css?family=Fira+Sans:400,300,300italic,500|Oswald:400,300,700|Montserrat' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Raleway:400,300' rel='stylesheet' type='text/css'>

      <!-- STYLESHEETS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

      
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>  


  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">

        <a class="navbar-brand" href="/">OBSCURA</a>
      </div> 

    
  <div>

    <ul class="nav navbar-nav navbar pull-right">

      <li class="dropdown">
      <% if !current_user %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
        <ul id="login-dp" class="dropdown-menu pull-right">
        <div class="form-group">
            <%= form_for :user, url: "/sessions", method: "post" do |f| %>
            <div>
              <%= f.text_field :email, placeholder: "Email",:class=>'form-control'%>
            </div>
            <div>
              <%= f.password_field :password, placeholder: "Password", :class=>'form-control' %>
            </div>

            <%= f.submit "Sign In", :class=> 'btn btn-primary btn-block'%>
            <% end %>
          </ul> 
        </div>


        <ul class="nav navbar-nav navbar pull-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Sign Up</b> <span class="caret"></span></a>
            <ul id="login-dp" class="dropdown-menu pull-right">
               <%= form_for :user, url: "/users", method: "post" do |f| %>
            <div>
              <%= f.text_field :first_name, placeholder: "First Name",:class=>'form-control'%>
            </div>

          <div>
            <%= f.text_field :last_name, placeholder: "Last Name",:class=>'form-control'%>
          </div>

          <div>
            <%= f.text_field :email, placeholder: "Email",:class=>'form-control'%>
          </div>

          <div>
            <%= f.password_field :password, placeholder: "Password",:class=>'form-control'%>
          </div>

          <div>
            <%= f.text_field :confirmation_code, placeholder: "Contributor Code" ,:class=>'form-control'%>
            <%= f.hidden_field :admin, value: false %>
          </div>

            <%= f.submit "Sign Up",:class=> 'btn btn-primary btn-block' %>
            <% end %>
        </ul>

  <% else %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b> <%= current_user.first_name %></b> <span class="caret"></span></a>
          <ul id="login-dp" class="dropdown-menu pull-right">
          <%= link_to user_path(session[:user_id]) do %>
            Profile
          <%end%>


        <a href="#"><%= button_to "Log Out", logout_path, :method => :delete, :class=> 'btn btn-primary btn-block' %></a>
        <% end %>
        </li>


      </div><!-- /.navbar-collapse -->
    <!-- /.container-fluid -->
  </nav>
  <br><br><br>


</body>

app/views/cities/index.html.erb
<body> 
  <div class="container-fluid">
   <section id="coverVideo" class="video">
    
      <div class="row">
            <!-- ===== VIDEO ===== -->
          
            <%= video_tag(["splashvideo.mp4", "splashvideo.webm", "splashvideo.ogv"], size: "cover", controls: false, autobuffer: false, autoplay: true, loop: true) %>

              <div class="col-sm-12 text-center">
                 <div class="title">Obscura</div>
                  <p class="subtitle">A Travel Community worth discovering.</p>
              </div>
            </video>
      </div>
    </section>

      <div class="text-center">
        <h2>About Us</h2><hr>
      </div>
          <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <p class="about">
            We are a travel guide showcasing hidden gems throughout the West Coast. Check out our featured cities below...Food and Beverages, Accomodation, Art, and Lifestyle. Real recommendations, skip the tourism. We help you have a trip worth remembering.
            </p>
          </div>

            <div class="row-fluid cities">
                <div class="col-sm-2 col-sm-offset-2"><div class="box"></div></div>
                <div class="col-sm-2"><div class="box"></div></div>
                <div class="col-sm-2"><div class="box"></div></div>
                <div class="col-sm-2"><div class="box"></div></div>
            </div>  
        </div>

                  <div class="row-fluid cities">
                <div class="col-sm-8 col-sm-offset-2">

                    <% @cities.each do |city| %>
                      <div class="col-sm-3 box">
                       <%= link_to city_path(city) do %>
                       <div class="crop cityshow" style="background-image: url(<%= city.url%>)">
                        <h3><%= city.name %></h3> 
                       <!--  <img class="crop" src='<%= city.url%>' /> -->
                        </div> 
                      <% end %>
                            
                          </div>    
                          <% end %>           
                </div>

            </div>  


      
    

</body>

app/views/cities/new.html.erb
<div class="row">
    <div class="col-sm-12 text-center">

      <div class="col-xs-12 col-sm-6 col-sm-offset-3 colorform">
        <%= form_for @city do |f| %>
          <div>
            <%= f.text_field :name, placeholder: "City Name" %>
          </div>
          <div>
            <%= f.text_field :description, placeholder: "Description" %>
          </div>
          <div>
            <%= f.text_field :url, placeholder: "Image URL" %>
          </div>
          <%= f.submit "Create City", :class=> 'btn btn-primary btn-block' %>
        <% end %>
      </div>

app/views/cities/show.html.erb
<!-- ===================== SINGLE CITY LANDING PAGE ====================== -->
	
<body><br>
	<!-- <div class="container"> -->
		<div class="row-fluid">
			<div class="text-center">
				<h1 class="responsive">Transforming your travel experience.</h1>
			</div><hr>

		<!-- ==== MAIN CITY SPLASH PHOTO ===== -->

			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="cityImage">
					<img src="<%= @city.url %>"/>
				</div>
			</div>
		</div>


	  <div class="row">
      <p class="text-center"><%= button_to "Add New Post", new_city_post_path(@city), :method => 'get' %></p>
      <% @city.features.each do |feature| %>
        <div class="col-xs-12 col-sm-5 col-sm-offset-1">
          <h2 class="text-center"><%= feature.title %></h2><hr>
          <% feature.posts.each do |post| %>
          <div class="thumbnail">
              <img  class="img-responsive" src="<%= post.imageUrl %>"> 
              <div class="caption">
                <h3><%= post.title %></h3>
                  <p><%= post.content %></p>
                  <%= link_to "Edit", edit_city_post_path(@city, post) %>
                  <%= link_to "Delete", city_post_path(@city, post), method: :delete %>
              </div>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>


</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>

<%= render 'html_header' %>

<body>

<%= yield %>
            
</body>



</html>

app/views/posts/edit.html.erb
div class="row">
    <div class="col-sm-12 text-center">

      <div class="col-xs-12 col-sm-6 col-sm-offset-3 colorform">

<%= form_for [@city, @post] do |f| %>

  <div>
    <%= f.text_field :title, placeholder: "Venue Name" %>
  </div>
  <div>
    <%= f.text_field :content, placeholder: "Description" %>
  </div>
  <div>
    <%= f.collection_select(:feature_id, Feature.all, :id, :title) %>
  </div>
  <div>
    <%= f.text_field :imageUrl, placeholder: "Image URL" %>
  </div>

  <%= f.submit "Edit Venue", :class=> 'btn btn-primary btn-block' %>
<% end %>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-sm-12 text-center">

      <div class="col-xs-12 col-sm-6 col-sm-offset-3 colorform">

<%= form_for [@city, @post] do |f| %>

  <div>
    <%= f.text_field :title, placeholder: "Venue Name" %>
  </div>
  <div>
    <%= f.text_field :content, placeholder: "Description" %>
  </div>
  <div>
    <%= f.collection_select(:feature_id, Feature.all, :id, :title) %>
  </div>
  <div>
    <%= f.text_field :imageUrl, placeholder: "Image URL" %>
  </div>

  <%= f.submit "Create Venue", :class=> 'btn btn-primary btn-block' %>
<% end %>

app/views/users/index.html.erb
<h1>welcome to users index</h1>

<div>
  this will be our users' profile page
</div>

app/views/users/new.html.erb
Sign Up

<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= f.text_field :confirmation_code, placeholder: "Contributor Code" %>
    <%= f.hidden_field :admin, value: false %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<body>
<div class="container">
<div class="username">
 <h2 class="text-center" style="font-weight:bold"><%= @user.first_name %> <%= @user.last_name %></h2>
</div>
<% if @user.admin %>

    <div class='col-sm-2 col-sm-offset-5'>
      <p><%= link_to "Create New City", new_city_path, :method => 'get', :class=> 'btn btn-primary btn-block' %></p>
    </div>
    <br>
    <h2 class="text-center">TRIPS CREATED</h2>
	
<% end %>
<div>
  <h2 class="text-center">TRIPS SAVED</h2>
</div>
</body>
</div>